package dotgitdex

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/Joker-of-Gotham/gitdex/internal/git"
	"github.com/Joker-of-Gotham/gitdex/internal/git/status"
)

// WriteGitContent serialises GitState into a structured text file at
// maintain/git-content.txt, following the schema:
// repo_path, current branch, per-branch working/staging/HEAD,
// remotes, ahead-behind, conflict flags, stash, submodules, etc.
func (m *Manager) WriteGitContent(state *status.GitState) error {
	if state == nil {
		return nil
	}
	var b strings.Builder

	b.WriteString("# Git Context — generated by Gitdex\n")
	b.WriteString(fmt.Sprintf("# Snapshot at %s\n\n", time.Now().Format(time.RFC3339)))

	// Current branch
	b.WriteString(fmt.Sprintf("current_branch: %s\n", state.LocalBranch.Name))
	if state.LocalBranch.IsDetached {
		b.WriteString("detached_head: true\n")
	}
	b.WriteString(fmt.Sprintf("head_ref: %s\n", state.HeadRef))
	b.WriteString(fmt.Sprintf("is_initial: %v\n", state.IsInitial))
	b.WriteString(fmt.Sprintf("commit_count: %d\n", state.CommitCount))
	if state.RepoConfig.DefaultBranch != "" {
		b.WriteString(fmt.Sprintf("default_branch: %s\n", state.RepoConfig.DefaultBranch))
	}

	// Branches
	if len(state.BranchDetails) > 0 {
		b.WriteString("\n## Local Branches\n")
		for _, bd := range state.BranchDetails {
			marker := " "
			if bd.IsCurrent {
				marker = "*"
			}
			line := fmt.Sprintf("%s %s", marker, bd.Name)
			if bd.Upstream != "" {
				line += fmt.Sprintf(" -> %s", bd.Upstream)
			}
			if bd.Ahead > 0 || bd.Behind > 0 {
				line += fmt.Sprintf(" [ahead %d, behind %d]", bd.Ahead, bd.Behind)
			}
			if bd.IsMerged {
				line += " (merged)"
			}
			if bd.LastCommit != "" {
				line += fmt.Sprintf(" | %s", bd.LastCommit)
			}
			b.WriteString(line + "\n")
		}
	} else if len(state.LocalBranches) > 0 {
		b.WriteString("\n## Local Branches\n")
		for _, name := range state.LocalBranches {
			b.WriteString(fmt.Sprintf("  %s\n", name))
		}
	}

	if len(state.MergedBranches) > 0 {
		b.WriteString("\n## Merged Branches\n")
		for _, name := range state.MergedBranches {
			b.WriteString(fmt.Sprintf("  %s\n", name))
		}
	}

	if len(state.RemoteBranches) > 0 {
		b.WriteString("\n## Remote Branches\n")
		for _, name := range state.RemoteBranches {
			b.WriteString(fmt.Sprintf("  %s\n", name))
		}
	}

	// Remotes
	if len(state.RemoteInfos) > 0 {
		b.WriteString("\n## Remotes\n")
		for _, r := range state.RemoteInfos {
			b.WriteString(fmt.Sprintf("  %s  fetch=%s  push=%s\n", r.Name, r.FetchURL, r.PushURL))
		}
	}

	// Upstream sync
	if state.UpstreamState != nil {
		b.WriteString(fmt.Sprintf("\n## Upstream\n  %s  ahead=%d  behind=%d\n",
			state.UpstreamState.Name, state.UpstreamState.Ahead, state.UpstreamState.Behind))
	}
	if len(state.AheadCommits) > 0 {
		b.WriteString("\n## Ahead Commits\n")
		for _, c := range state.AheadCommits {
			b.WriteString(fmt.Sprintf("  %s\n", c))
		}
	}
	if len(state.BehindCommits) > 0 {
		b.WriteString("\n## Behind Commits\n")
		for _, c := range state.BehindCommits {
			b.WriteString(fmt.Sprintf("  %s\n", c))
		}
	}

	// Working tree (exclude .gitdex/ entries)
	if len(state.WorkingTree) > 0 {
		var filtered []git.FileStatus
		for _, f := range state.WorkingTree {
			if !isGitdexPath(f.Path) {
				filtered = append(filtered, f)
			}
		}
		if len(filtered) > 0 {
			b.WriteString("\n## Working Tree Changes\n")
			for _, f := range filtered {
				b.WriteString(fmt.Sprintf("  %c %s\n", byte(f.WorktreeCode), f.Path))
			}
		}
	}

	// Staging area (exclude .gitdex/ entries)
	if len(state.StagingArea) > 0 {
		var filtered []git.FileStatus
		for _, f := range state.StagingArea {
			if !isGitdexPath(f.Path) {
				filtered = append(filtered, f)
			}
		}
		if len(filtered) > 0 {
			b.WriteString("\n## Staging Area\n")
			for _, f := range filtered {
				b.WriteString(fmt.Sprintf("  %c %s\n", byte(f.StagingCode), f.Path))
			}
		}
	}

	// Repository state flags
	writeFlag := func(name string, val bool) {
		if val {
			b.WriteString(fmt.Sprintf("  %s: true\n", name))
		}
	}
	b.WriteString("\n## Repository State\n")
	writeFlag("merge_in_progress", state.MergeInProgress)
	writeFlag("rebase_in_progress", state.RebaseInProgress)
	writeFlag("cherry_pick_in_progress", state.CherryInProgress)
	writeFlag("bisect_in_progress", state.BisectInProgress)
	writeFlag("has_gitignore", state.HasGitIgnore)
	writeFlag("has_gitattributes", state.HasGitAttributes)

	// Stash
	if len(state.StashStack) > 0 {
		b.WriteString("\n## Stash\n")
		for _, s := range state.StashStack {
			b.WriteString(fmt.Sprintf("  stash@{%d}: %s\n", s.Index, s.Message))
		}
	}

	// Submodules
	if len(state.Submodules) > 0 {
		b.WriteString("\n## Submodules\n")
		for _, s := range state.Submodules {
			b.WriteString(fmt.Sprintf("  %s  path=%s  url=%s  status=%s\n", s.Name, s.Path, s.URL, s.Status))
		}
	}

	// Tags
	if len(state.Tags) > 0 {
		b.WriteString("\n## Tags\n")
		for _, t := range state.Tags {
			b.WriteString(fmt.Sprintf("  %s\n", t))
		}
	}

	// Reflog
	if len(state.RecentReflog) > 0 {
		b.WriteString("\n## Recent Reflog\n")
		for _, r := range state.RecentReflog {
			b.WriteString(fmt.Sprintf("  %s\n", r))
		}
	}

	// Worktrees
	if len(state.Worktrees) > 0 {
		b.WriteString("\n## Worktrees\n")
		for _, w := range state.Worktrees {
			b.WriteString(fmt.Sprintf("  %s\n", w))
		}
	}

	if state.DescribeTag != "" {
		b.WriteString(fmt.Sprintf("\ndescribe_tag: %s\n", state.DescribeTag))
	}

	// Config info
	if state.ConfigInfo != nil {
		b.WriteString("\n## Config\n")
		ci := state.ConfigInfo
		if ci.UserName != "" {
			b.WriteString(fmt.Sprintf("  user.name: %s\n", ci.UserName))
		}
		if ci.UserEmail != "" {
			b.WriteString(fmt.Sprintf("  user.email: %s\n", ci.UserEmail))
		}
		if ci.DefaultBranch != "" {
			b.WriteString(fmt.Sprintf("  init.defaultBranch: %s\n", ci.DefaultBranch))
		}
		if ci.CoreAutoCRLF != "" {
			b.WriteString(fmt.Sprintf("  core.autocrlf: %s\n", ci.CoreAutoCRLF))
		}
		if ci.PullRebase != "" {
			b.WriteString(fmt.Sprintf("  pull.rebase: %s\n", ci.PullRebase))
		}
	}

	// File inspection summary
	if state.FileInspect != nil {
		fi := state.FileInspect
		b.WriteString(fmt.Sprintf("\n## File Inspection\n  total_tracked: %d\n", fi.TotalFiles))
		if len(fi.ImportantFiles) > 0 {
			b.WriteString("  important_files: " + strings.Join(fi.ImportantFiles, ", ") + "\n")
		}
	}

	// Commit summary
	if state.CommitSummaryInfo != nil {
		cs := state.CommitSummaryInfo
		b.WriteString("\n## Commit Summary\n")
		if cs.UsesConventional {
			b.WriteString("  conventional_commits: true\n")
		}
		if cs.CommitFrequency != "" {
			b.WriteString(fmt.Sprintf("  commit_frequency: %s\n", cs.CommitFrequency))
		}
		if cs.LastCommitRelative != "" {
			b.WriteString(fmt.Sprintf("  last_commit: %s\n", cs.LastCommitRelative))
		}
		if len(cs.RecentCommits) > 0 {
			b.WriteString("  recent_commits:\n")
			for _, msg := range cs.RecentCommits {
				b.WriteString(fmt.Sprintf("    - %s\n", msg))
			}
		}
	}

	// Dirty summary (exclude .gitdex/ from counts)
	wt := 0
	for _, f := range state.WorkingTree {
		if !isGitdexPath(f.Path) {
			wt++
		}
	}
	sa := 0
	for _, f := range state.StagingArea {
		if !isGitdexPath(f.Path) {
			sa++
		}
	}
	b.WriteString(fmt.Sprintf("\n## Summary\n  working_tree_dirty: %d\n  staging_area_dirty: %d\n", wt, sa))

	_ = git.RiskSafe // keep import valid

	return os.WriteFile(m.GitContentPath(), []byte(b.String()), 0o644)
}

func isGitdexPath(path string) bool {
	return strings.HasPrefix(path, ".gitdex/") || strings.HasPrefix(path, ".gitdex\\") || path == ".gitdex"
}

// ReadGitContent returns the content of maintain/git-content.txt.
func (m *Manager) ReadGitContent() (string, error) {
	data, err := os.ReadFile(m.GitContentPath())
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}
